name: Upload Website to AWS S3

on:
  workflow_dispatch:
  push:
    paths:
      - "frontend/**"
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  aws-deploy:
    name: Upload to S3
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/
      - run: npm ci --prefix frontend
      - run: npm run build --prefix frontend
        env:
          VITE_APP_BASE_URL: ${{ vars.VITE_APP_BASE_URL }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.PREFIX }}-githubactions-assume-role
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload To S3
        run: aws s3 cp --recursive frontend/dist s3://${{ vars.AWS_DEPLOY_BUCKET }}/ --cache-control "no-store"
